language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

addons:
  apt:
    packages:
      - libzmq-dev

before_script:
  - echo "yes" | pecl -d preferred_state=beta install zmq
  - composer install --dev

script: vendor/bin/phpunit --coverage-text
